name: presence_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sizer: ^2.0.13
  cloud_firestore: 4.3.0
  firebase_core: 2.4.0
  firebase_auth: 4.2.3
  firebase_storage: 11.0.9
  flutter_native_splash: ^2.2.8
  get_storage: ^2.0.2
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^8.3.0
  uuid: 3.0.7
  intl: ^0.17.0
  lottie: any
  flutter_map: ^0.14.0
  latlong: ^0.6.1
  image_picker: ^0.8.3+2
  image_cropper: any
  geolocator: ^9.0.2
  colorize_text_avatar: ^1.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/images/

